MVCWebApiTest/MVCWebApiTest/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCWebApiTest.Models
{
    public class UserViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public AddressViewModel Address { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public CompanyViewModel Company { get; set; }
        public List<UserPostsViewModel> Posts { get; set; }
    }

}

MVCWebApiTest/MVCWebApiTest/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using MVCWebApiTest.Models;
using Newtonsoft.Json;
using PagedList;

namespace MVCWebApiTest.Controllers
{
    public class AlbumsController : Controller
    {
        public async Task<ViewResult> Index(string currentFilter, string searchString, int? page)
        {
            if(searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            IEnumerable<AlbumViewModel> albums = null;
            IEnumerable<AlbumPhotoViewModel> photos = null;
            IEnumerable<UserViewModel> users = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var responseAlbums = await client.GetAsync("albums");

                if (responseAlbums.IsSuccessStatusCode)
                { 
                    var responseBody = await responseAlbums.Content.ReadAsStringAsync();

                    albums = JsonConvert.DeserializeObject<IEnumerable<AlbumViewModel>>(responseBody).OrderBy(a => a.Id);
                }

                var responseAlbumPhotos = await client.GetAsync("photos");

                if (responseAlbumPhotos.IsSuccessStatusCode)
                {
                    var responseBody = await responseAlbumPhotos.Content.ReadAsStringAsync();

                    photos = JsonConvert.DeserializeObject<IEnumerable<AlbumPhotoViewModel>>(responseBody);
                }

                var responseUsers = await client.GetAsync("users");

                if (responseUsers.IsSuccessStatusCode)
                {
                    var responseBody = await responseUsers.Content.ReadAsStringAsync();

                    users = JsonConvert.DeserializeObject<IEnumerable<UserViewModel>>(responseBody);
                }

                foreach (var album in albums.ToList())
                {
                    var albumPhotos = photos.Where(p => p.AlbumId == album.Id);

                    var photoList = new List<AlbumPhotoViewModel>();
                    foreach(var photo in albumPhotos)
                    {
                        photoList.Add(photo);
                    }
                    album.Photos = photoList;

                    album.User = users.SingleOrDefault(u => u.Id == album.UserId);
                }
            }

            if(!string.IsNullOrWhiteSpace(searchString))
            {

                albums = albums.Where(a => 
                    a.User.Name.IndexOf(searchString, StringComparison.InvariantCultureIgnoreCase) >= 0 ||
                    a.Title.IndexOf(searchString, StringComparison.InvariantCultureIgnoreCase) >= 0
                    ).ToList();
            }

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(albums.ToPagedList(pageNumber,pageSize));
        }

        public async Task<ViewResult> AlbumDetails(int id)
        {
            var album = new AlbumViewModel();

            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var response = await client.GetAsync($"albums/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var responseBody = await response.Content.ReadAsStringAsync();

                    album = JsonConvert.DeserializeObject<AlbumViewModel>(responseBody);
                }

                var responsePosts = await client.GetAsync($"albums/{id}/photos");

                if (responsePosts.IsSuccessStatusCode)
                {
                    var responseBody = await responsePosts.Content.ReadAsStringAsync();

                    var photos = JsonConvert.DeserializeObject<List<AlbumPhotoViewModel>>(responseBody);

                    if (album != null)
                        album.Photos = photos.OrderBy(p => p.Id).ToList();
                }
            }

            return View(album);
        }
    }
}

MVCWebApiTest/MVCWebApiTest/Controllers/UserController.cs
using MVCWebApiTest.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCWebApiTest.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public async Task<ActionResult> Index(int id)
        {
            var user = new UserViewModel();

            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var response = await client.GetAsync($"users/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var responseBody = await response.Content.ReadAsStringAsync();

                    user = JsonConvert.DeserializeObject<UserViewModel>(responseBody);
                }

                var responsePosts = await client.GetAsync($"users/{id}/posts");

                if(responsePosts.IsSuccessStatusCode)
                {
                    var responseBody = await responsePosts.Content.ReadAsStringAsync();

                    var posts = JsonConvert.DeserializeObject<List<UserPostsViewModel>>(responseBody);

                    if (user != null)
                        user.Posts = posts.OrderBy(p => p.Id).ToList();
                        
                }
            }

            return View(user);
        }
    }
}

MVCWebApiTest/MVCWebApiTest/Views/User/Index.cshtml
@model MVCWebApiTest.Models.UserViewModel

@{
    ViewBag.Title = "User";
}

<h2>User</h2>

<div>
    <h4>User Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            User Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Suite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.Suite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Geo.Lat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.Geo.Lat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address.Geo.Lng)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.Geo.Lng)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>

        <dt>
            Catch Phrase
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CatchPhrase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.Bs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.Bs)
        </dd>
    </dl>
</div>

<h3>Posts</h3>
<br />
<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Body
        </th>
    </tr>

    @foreach (var item in Model.Posts)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
        </tr>
    }
</table>

<p>
    @Html.ActionLink("Back to Album List", "Index", "Albums")
</p>